#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  jsonValidationError:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Date has failed validation. Needs to be in format dd-MM-yyyy
              value:
                code: BAD_REQUEST
                path: historicAddress[0].startDate

  apiServiceError:
    responses:
      500:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: When there is an internal error within the service
              value:
                code: INTERNAL_SERVER_ERROR

  authorizationError:
    responses:
      401:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: When the user fails to authenticate.
              value:
                code: UNAUTHORIZED
                message: Invalid bearer token

  authDownError:
    responses:
      502:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Auth is currently down.
              value:
                code: BAD_GATEWAY
                message: Auth is currently down.

  downstream5xxError:
    responses:
      500:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: When a downstream 5xx error occurs, but isn't a 502.
              value:
                code: INTERNAL_SERVER_ERROR
                message: An internal server error occurred
