displayName: Get API Definition
description: Returns a description of the API
responses:
  200:
    body:
      application/json:
        type: !include schema/definition/definition-get.json
        example:
          description: Typical response received
          example: !include examples/definition/definition-get.json
