#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

# Example for when we start using errors
#traits:
#  apiServiceError:
#    responses:
#      500:
#        body:
#          application/json:
#            type: types.errorResponse
#            example:
#              description: When there is an internal error within the service
#              value:
#                code: INTERNAL_SERVER_ERROR
