#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  contentTypeJson:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be JSON.
        type: string
        required: true
        example: application/json
  acceptJson:
    headers:
      Accept:
        description: Specifies the response format and the version of the API to use.
        type: string
        required: true
        example: 'application/vnd.hmrc.1.0+json'
  correlationID:
    headers:
      CorrelationId:
        description: A UUID identifier of the transaction.
        type: string
        required: true
        example: 'a1e8057e-fbbc-47a8-a8b4-78d9f015c253'
   originatorID:
    headers:
      OriginatorId:
        description: Mandatory. Consumer ID
        type: string
        required: true
        example: 'DA2_DWP_REG'
