#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  contentTypeJson:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be JSON.
        type: string
        required: true
        example: application/json
  acceptJson:
    headers:
      Accept:
        description: Specifies the response format and the version of the API to use.
        type: string
        required: true
        example: 'application/vnd.hmrc.1.0+json'
